/** Shared permission catalog for MediFlow RBAC UI + auth helpers. */
export const PERMISSION_CATALOG: Array<{ module: string; code: string; name: string; description: string }> = [
  { module: 'dashboard', code: 'dashboard.view', name: 'View Dashboard', description: 'Access dashboard' },
  { module: 'users', code: 'users.view', name: 'View Users', description: 'List/view users' },
  { module: 'users', code: 'users.create', name: 'Create Users', description: 'Create new users' },
  { module: 'users', code: 'users.edit', name: 'Edit Users', description: 'Edit user details' },
  { module: 'users', code: 'users.deactivate', name: 'Deactivate Users', description: 'Suspend/Deactivate users' },
  { module: 'users', code: 'users.manage_roles', name: 'Manage Roles', description: 'Create/edit roles' },
  { module: 'users', code: 'users.manage_permissions', name: 'Manage Permissions', description: 'Assign permissions' },
  { module: 'users', code: 'users.manage', name: 'Manage Users (legacy)', description: 'Legacy full user management' },
  { module: 'products', code: 'products.view', name: 'View Products', description: 'View products' },
  { module: 'products', code: 'products.create', name: 'Create Products', description: 'Create products' },
  { module: 'products', code: 'products.edit', name: 'Edit Products', description: 'Edit products' },
  { module: 'products', code: 'products.delete', name: 'Delete Products', description: 'Archive products' },
  { module: 'products', code: 'products.import', name: 'Import Products', description: 'Bulk import' },
  { module: 'products', code: 'products.export', name: 'Export Products', description: 'Export products' },
  { module: 'inventory', code: 'inventory.view', name: 'View Inventory', description: 'View inventory' },
  { module: 'inventory', code: 'inventory.receive', name: 'Receive Inventory', description: 'Goods receiving' },
  { module: 'inventory', code: 'inventory.adjust', name: 'Adjust Inventory', description: 'Stock adjustments' },
  { module: 'inventory', code: 'inventory.stock_take', name: 'Stock Take', description: 'Stock counts' },
  { module: 'inventory', code: 'inventory.transfer', name: 'Transfer Stock', description: 'Inter-branch transfer' },
  { module: 'inventory', code: 'inventory.approve_adjustment', name: 'Approve Adjustments', description: 'Approve stock adjustments' },
  { module: 'purchases', code: 'purchases.view', name: 'View Purchases', description: 'View POs' },
  { module: 'purchases', code: 'purchases.create', name: 'Create Purchases', description: 'Create POs' },
  { module: 'purchases', code: 'purchases.approve', name: 'Approve Purchases', description: 'Approve POs' },
  { module: 'purchases', code: 'purchases.receive', name: 'Receive Purchases', description: 'GRN' },
  { module: 'purchases', code: 'purchases.return', name: 'Return Purchases', description: 'Purchase returns' },
  { module: 'sales', code: 'sales.view', name: 'View Sales', description: 'View sales' },
  { module: 'sales', code: 'sales.create', name: 'Create Sales', description: 'POS/ sales creation' },
  { module: 'sales', code: 'sales.edit_draft', name: 'Edit Draft Sales', description: 'Edit held sales' },
  { module: 'sales', code: 'sales.void', name: 'Void Sales', description: 'Void sales' },
  { module: 'sales', code: 'sales.return', name: 'Process Returns', description: 'Sales returns' },
  { module: 'sales', code: 'sales.discount', name: 'Apply Discount', description: 'Apply discounts' },
  { module: 'sales', code: 'sales.price_override', name: 'Price Override', description: 'Override selling price' },
  { module: 'expenses', code: 'expenses.view', name: 'View Expenses', description: 'View expenses' },
  { module: 'expenses', code: 'expenses.create', name: 'Create Expenses', description: 'Create expenses' },
  { module: 'expenses', code: 'expenses.approve', name: 'Approve Expenses', description: 'Approve expenses' },
  { module: 'expenses', code: 'expenses.pay', name: 'Pay Expenses', description: 'Pay expenses' },
  { module: 'expenses', code: 'expenses.void', name: 'Void Expenses', description: 'Void expenses' },
  { module: 'customers', code: 'customers.view', name: 'View Customers', description: 'View customers' },
  { module: 'customers', code: 'customers.create', name: 'Create Customers', description: 'Create customers' },
  { module: 'customers', code: 'customers.edit', name: 'Edit Customers', description: 'Edit customers' },
  { module: 'customers', code: 'customers.credit', name: 'Manage Credit', description: 'Credit adjustments' },
  { module: 'customers', code: 'customers.view_financials', name: 'View Customer Financials', description: 'Financials' },
  { module: 'customers', code: 'customers.manage', name: 'Manage Customers (legacy)', description: 'Legacy' },
  { module: 'suppliers', code: 'suppliers.view', name: 'View Suppliers', description: 'View suppliers' },
  { module: 'suppliers', code: 'suppliers.create', name: 'Create Suppliers', description: 'Create suppliers' },
  { module: 'suppliers', code: 'suppliers.edit', name: 'Edit Suppliers', description: 'Edit suppliers' },
  { module: 'suppliers', code: 'suppliers.view_financials', name: 'View Supplier Financials', description: 'Financials' },
  { module: 'reports', code: 'reports.view', name: 'View Reports', description: 'Operational reports' },
  { module: 'reports', code: 'reports.export', name: 'Export Reports', description: 'Export reports' },
  { module: 'reports', code: 'reports.view_financial', name: 'View Financial Reports', description: 'Finance P&L' },
  { module: 'reports', code: 'reports.view_profit', name: 'View Profit', description: 'Margin/profit' },
  { module: 'reports', code: 'reports.view_costs', name: 'View Costs', description: 'Cost visibility' },
  { module: 'settings', code: 'settings.view', name: 'View Settings', description: 'View settings' },
  { module: 'settings', code: 'settings.edit', name: 'Edit Settings', description: 'Edit settings' },
  { module: 'settings', code: 'settings.manage', name: 'Manage Settings (legacy)', description: 'Legacy' },
  { module: 'settings', code: 'settings.manage_tax', name: 'Manage Tax', description: 'Tax settings' },
  { module: 'settings', code: 'settings.manage_branches', name: 'Manage Branches', description: 'Branch config' },
  { module: 'audit', code: 'audit.view', name: 'View Audit', description: 'Audit logs' },
  { module: 'audit', code: 'audit.export', name: 'Export Audit', description: 'Export audit' },
];

export const NAV_PERMISSION_MAP: Record<string, string | null> = {
  '/dashboard': 'dashboard.view',
  '/pos': 'sales.create',
  '/cash': 'sales.create',
  '/products': 'products.view',
  '/inventory': 'inventory.view',
  '/purchases': 'purchases.view',
  '/suppliers': 'suppliers.view',
  '/sales': 'sales.view',
  '/returns': 'sales.return',
  '/expenses': 'expenses.view',
  '/customers': 'customers.view',
  '/reports': 'reports.view',
  '/users': 'users.view',
  '/audit': 'audit.view',
  '/settings': 'settings.view',
};
